name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show files
      run: ls

    - name: Build step
      run: echo "Build successful 🚀"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      run: echo "Deploying 🚀"